---
- name: Install EPEL repository on CentOS
  yum:
    name: epel-release
    state: present

- name: Install Nagios dependencies on CentOS
  yum: 
    name: 
      - httpd
      - nagios
    state: present

- name: Start and enable Nagios service on CentOS
  systemd:
    name: nagios
    enabled: yes
    state: started
